services:
  sandbox:
    image: sandbox
    user: ${USER}
    build:
      args: 
        user: ${USER}
        rootpassword: ${DC_ROOTPASSWORD}
      dockerfile: Dockerfile202504
      context: ./customizations
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${HOME}/${DC_FOLDER}:/home/${USER}
    #- ${HOME}/.zshrc:/home/${USER}/.zshrc
    #- ${HOME}/.ssh:/home/${USER}/.ssh
    #- ${HOME}/.oh-my-zsh:/home/${USER}/.oh-my-zsh
    hostname: sandbox